### PR TITLE
Show percentage change

### PR DESCRIPTION
**Pull request by pavel-dudek**
### Refence a related issue

This pull request solves #2

### Description of the changes

- changed text to be analyzed

### Mentions

Person responsible for reviewing: @pavel-school

### CODE REVIEW

**Review by pavel-dudek — COMMENTED** [review]
changes are ok

**Review by pavel-dudek — COMMENTED** [review]
ok

**Comment by pavel-school** [comment]
forcing the merge.

**Review by pavel-school — APPROVED** [review]
ok

**Pull request merged**
